#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__ . '/../vendor/autoload.php';

$app = new Silex\Application();

$app->register(new Knp\Provider\ConsoleServiceProvider(), array(
    'console.name'              => 'GamTableau',
    'console.version'           => '1.0.0',
    'console.project_directory' => __DIR__.'/..'
));

$console = $app['console'];

$console->add(new Creative\Command\AddCreativeToLinesInOrderCommand($app));
$console->add(new Creative\Command\AssociateCreativesInOrderCommand($app));
$console->add(new Creative\Command\CreativeCommand($app));
$console->add(new Creative\Command\DeactivateAssociatedCreativesInOrderCommand($app));
$console->add(new Creative\Command\RemoveCreativesInOrderCommand($app));

$console->add(new Inventory\Command\ArchiveAdUnitsCommand($app));
$console->add(new Inventory\Command\ChildContentEligibilityUpdateCommand($app));
$console->add(new Inventory\Command\CreateLineItemsCommand($app));
$console->add(new Inventory\Command\KeyValuesGetterCommand($app));
$console->add(new Inventory\Command\KeyValuesRemoveCommand($app));
$console->add(new Inventory\Command\SuggestedAdUnitsCommand($app));

$console->add(new LineItem\Command\FindLineItemByKeyCommand($app));
$console->add(new LineItem\Command\LineItemSizesAlterCommand($app));
$console->add(new LineItem\Command\LineItemKeyValuesAddCommand($app));
$console->add(new LineItem\Command\LineItemKeyValuesUpdateCommand($app));
$console->add(new LineItem\Command\LineItemKeyValuesRemoveCommand($app));
$console->add(new LineItem\Command\OrderLineItemsKeyRenameCommand($app));
$console->add(new LineItem\Command\OrderLineItemsKeyValuesAddCommand($app));
$console->add(new LineItem\Command\OrderLineItemsKeyValuesRemoveCommand($app));

$console->run();
