queries:
  hourlyRecoveredImpressions:
    dimensions:
      - creative_name
      - creative_size
    metrics:
      - total_active_view_eligible_impressions
    filters:
      creative_id:
        - 105924537612
        - 105924537732
        - 105925466892
        - 105925599852
      targeting_value_id:
#       src=rec
        - 228287954892
  hourlyImpressionsNonUS:
    dimensions:
      - country
    metrics:
      - total_active_view_eligible_impressions
    filters:
      country:
        - United Kingdom
        - Germany
        - Australia
        - Canada
        - Denmark
        - Poland
        - Russia
        - China
        - Hong Kong
        - Japan
