apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dfp-query-tool
spec:
  # every minute
  schedule: "0 */4 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dfp-query-tool
            image: artifactory.wikia-inc.com/aden/dfp-query-tool:0.0.1
            args:
            - ./approve.sh
            volumeMounts:
            - name: adeng-query-tool-credentials
              mountPath: /etc/adeng-query-tool-credentials
          restartPolicy: Never
          volumes:
          - name: adeng-query-tool-credentials
            secret:
              secretName: adeng-query-tool-credentials
      backoffLimit: 4
